version: 0.2

env:
  shell: bash
  variables:
    # These variables may be over-ridden as appropriate by the CI/CD pipeline
    NEXTFLOW_IMAGE_NAME: "nextflow"
    NEXTFLOW_VERSION: "23.10.1"
    AWS_REGION: "ap-southeast-1"
    AWS_ACCOUNT_ID: 026171442599

phases:
  pre_build:
    commands:
      - NEXTFLOW_IMAGE_URI=${NEXTFLOW_IMAGE_NAME}:${NEXTFLOW_VERSION}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - docker build -t ${NEXTFLOW_IMAGE_URI} --build-arg NEXTFLOW_VERSION=${NEXTFLOW_VERSION} .
  post_build:
    commands:
      - docker save -o nextflow_image.tar ${NEXTFLOW_IMAGE_URI}
      - docker tag ${NEXTFLOW_IMAGE_URI}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${NEXTFLOW_IMAGE_URI}:latest
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${NEXTFLOW_IMAGE_URI}     

artifacts:
  files:
    - nextflow_image.tar
