version: 0.2

env:
  shell: bash
  variables:
    # These variables may be over-ridden as appropriate by the CI/CD pipeline
    AWS_REGION: "ap-southeast-1"
    AWS_ACCOUNT_ID: 026171442599

phases:
  pre_build:
    commands:
      - echo Starting build of wes_adapter...
      # install python3.9 on amazon linux 2
      - sudo amazon-linux-extras install python3.9
      - sudo yum install python3-pip -y
  build:
    commands:
      - chmod +x wes_adapeter/install.sh
      - ./wes_adapeter/install.sh
  post_build:
    commands:
      - echo Done building wes_adapter.

artifacts:
  files:
    - wes_adapter.zip
